### ISSUE TITLE
Changing of sherpa-onnx-wasm-main.data Not enough

### ISSUE THREAD

**Issue by gyroing** [DavidCks/piper-wasm#1]
![Screenshot_20240224_195257_Chrome](https://github.com/DavidCks/piper-wasm/assets/3199486/ce0fa158-268a-483f-a9a7-6d79c55f6be7)
In the sherpa onnx Webassembly model, the information is packaged and loaded with preloading files. The binary address of each file is included in the corresponding format of its js file, so if the voice data file needs to be changed, the sherpa-onnx-wasm-main.js file, which corresponds to sherpa -onnx-wasm-main.data should also be changed . the "loadPackage" arraylist in the -onnx-wasm-main.js file, contains the beginning and end of binary address, each onnx model has its own size. and realted js file should be changed.
 in the description section of repo: Requirements A data file that is compatible with sherpa-onnx must include with **_related js file._**

**Comment by DavidCks** [comment]
Thanks for pointing that out! The package is still very early stages but that info will come in handy once I try to load my own custom voice model and inevitably run into these things. I'm sure you've noticed, but I basically just hacked the code from https://huggingface.co/spaces/k2-fsa/web-assembly-tts-sherpa-onnx-en/ to fit inside an npm package, so I haven't really delved into the code they wrote yet.
